// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zetasql-extract-table.proto

package com.tktkc72.zetasql_extract_table;

public final class ZetasqlExtractTable {
  private ZetasqlExtractTable() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ExtractTableNamesRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:extracttable.ExtractTableNamesRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string statement = 1;</code>
     * @return The statement.
     */
    java.lang.String getStatement();
    /**
     * <code>string statement = 1;</code>
     * @return The bytes for statement.
     */
    com.google.protobuf.ByteString
        getStatementBytes();
  }
  /**
   * Protobuf type {@code extracttable.ExtractTableNamesRequest}
   */
  public  static final class ExtractTableNamesRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:extracttable.ExtractTableNamesRequest)
      ExtractTableNamesRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ExtractTableNamesRequest.newBuilder() to construct.
    private ExtractTableNamesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExtractTableNamesRequest() {
      statement_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ExtractTableNamesRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ExtractTableNamesRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              statement_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.internal_static_extracttable_ExtractTableNamesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.internal_static_extracttable_ExtractTableNamesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest.class, com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest.Builder.class);
    }

    public static final int STATEMENT_FIELD_NUMBER = 1;
    private volatile java.lang.Object statement_;
    /**
     * <code>string statement = 1;</code>
     * @return The statement.
     */
    public java.lang.String getStatement() {
      java.lang.Object ref = statement_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        statement_ = s;
        return s;
      }
    }
    /**
     * <code>string statement = 1;</code>
     * @return The bytes for statement.
     */
    public com.google.protobuf.ByteString
        getStatementBytes() {
      java.lang.Object ref = statement_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        statement_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStatementBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, statement_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStatementBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, statement_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest)) {
        return super.equals(obj);
      }
      com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest other = (com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest) obj;

      if (!getStatement()
          .equals(other.getStatement())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATEMENT_FIELD_NUMBER;
      hash = (53 * hash) + getStatement().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code extracttable.ExtractTableNamesRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:extracttable.ExtractTableNamesRequest)
        com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.internal_static_extracttable_ExtractTableNamesRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.internal_static_extracttable_ExtractTableNamesRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest.class, com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest.Builder.class);
      }

      // Construct using com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        statement_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.internal_static_extracttable_ExtractTableNamesRequest_descriptor;
      }

      @java.lang.Override
      public com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest getDefaultInstanceForType() {
        return com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest build() {
        com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest buildPartial() {
        com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest result = new com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest(this);
        result.statement_ = statement_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest) {
          return mergeFrom((com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest other) {
        if (other == com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest.getDefaultInstance()) return this;
        if (!other.getStatement().isEmpty()) {
          statement_ = other.statement_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object statement_ = "";
      /**
       * <code>string statement = 1;</code>
       * @return The statement.
       */
      public java.lang.String getStatement() {
        java.lang.Object ref = statement_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          statement_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string statement = 1;</code>
       * @return The bytes for statement.
       */
      public com.google.protobuf.ByteString
          getStatementBytes() {
        java.lang.Object ref = statement_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          statement_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string statement = 1;</code>
       * @param value The statement to set.
       * @return This builder for chaining.
       */
      public Builder setStatement(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        statement_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string statement = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatement() {
        
        statement_ = getDefaultInstance().getStatement();
        onChanged();
        return this;
      }
      /**
       * <code>string statement = 1;</code>
       * @param value The bytes for statement to set.
       * @return This builder for chaining.
       */
      public Builder setStatementBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        statement_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:extracttable.ExtractTableNamesRequest)
    }

    // @@protoc_insertion_point(class_scope:extracttable.ExtractTableNamesRequest)
    private static final com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest();
    }

    public static com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExtractTableNamesRequest>
        PARSER = new com.google.protobuf.AbstractParser<ExtractTableNamesRequest>() {
      @java.lang.Override
      public ExtractTableNamesRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExtractTableNamesRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ExtractTableNamesRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExtractTableNamesRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ExtractTableNamesResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:extracttable.ExtractTableNamesResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string tableNames = 1;</code>
     * @return A list containing the tableNames.
     */
    java.util.List<java.lang.String>
        getTableNamesList();
    /**
     * <code>repeated string tableNames = 1;</code>
     * @return The count of tableNames.
     */
    int getTableNamesCount();
    /**
     * <code>repeated string tableNames = 1;</code>
     * @param index The index of the element to return.
     * @return The tableNames at the given index.
     */
    java.lang.String getTableNames(int index);
    /**
     * <code>repeated string tableNames = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the tableNames at the given index.
     */
    com.google.protobuf.ByteString
        getTableNamesBytes(int index);
  }
  /**
   * Protobuf type {@code extracttable.ExtractTableNamesResponse}
   */
  public  static final class ExtractTableNamesResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:extracttable.ExtractTableNamesResponse)
      ExtractTableNamesResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ExtractTableNamesResponse.newBuilder() to construct.
    private ExtractTableNamesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExtractTableNamesResponse() {
      tableNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ExtractTableNamesResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ExtractTableNamesResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                tableNames_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              tableNames_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          tableNames_ = tableNames_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.internal_static_extracttable_ExtractTableNamesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.internal_static_extracttable_ExtractTableNamesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse.class, com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse.Builder.class);
    }

    public static final int TABLENAMES_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList tableNames_;
    /**
     * <code>repeated string tableNames = 1;</code>
     * @return A list containing the tableNames.
     */
    public com.google.protobuf.ProtocolStringList
        getTableNamesList() {
      return tableNames_;
    }
    /**
     * <code>repeated string tableNames = 1;</code>
     * @return The count of tableNames.
     */
    public int getTableNamesCount() {
      return tableNames_.size();
    }
    /**
     * <code>repeated string tableNames = 1;</code>
     * @param index The index of the element to return.
     * @return The tableNames at the given index.
     */
    public java.lang.String getTableNames(int index) {
      return tableNames_.get(index);
    }
    /**
     * <code>repeated string tableNames = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the tableNames at the given index.
     */
    public com.google.protobuf.ByteString
        getTableNamesBytes(int index) {
      return tableNames_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < tableNames_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tableNames_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < tableNames_.size(); i++) {
          dataSize += computeStringSizeNoTag(tableNames_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getTableNamesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse)) {
        return super.equals(obj);
      }
      com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse other = (com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse) obj;

      if (!getTableNamesList()
          .equals(other.getTableNamesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTableNamesCount() > 0) {
        hash = (37 * hash) + TABLENAMES_FIELD_NUMBER;
        hash = (53 * hash) + getTableNamesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code extracttable.ExtractTableNamesResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:extracttable.ExtractTableNamesResponse)
        com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.internal_static_extracttable_ExtractTableNamesResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.internal_static_extracttable_ExtractTableNamesResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse.class, com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse.Builder.class);
      }

      // Construct using com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        tableNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.internal_static_extracttable_ExtractTableNamesResponse_descriptor;
      }

      @java.lang.Override
      public com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse getDefaultInstanceForType() {
        return com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse build() {
        com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse buildPartial() {
        com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse result = new com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          tableNames_ = tableNames_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.tableNames_ = tableNames_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse) {
          return mergeFrom((com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse other) {
        if (other == com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse.getDefaultInstance()) return this;
        if (!other.tableNames_.isEmpty()) {
          if (tableNames_.isEmpty()) {
            tableNames_ = other.tableNames_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTableNamesIsMutable();
            tableNames_.addAll(other.tableNames_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList tableNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTableNamesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          tableNames_ = new com.google.protobuf.LazyStringArrayList(tableNames_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string tableNames = 1;</code>
       * @return A list containing the tableNames.
       */
      public com.google.protobuf.ProtocolStringList
          getTableNamesList() {
        return tableNames_.getUnmodifiableView();
      }
      /**
       * <code>repeated string tableNames = 1;</code>
       * @return The count of tableNames.
       */
      public int getTableNamesCount() {
        return tableNames_.size();
      }
      /**
       * <code>repeated string tableNames = 1;</code>
       * @param index The index of the element to return.
       * @return The tableNames at the given index.
       */
      public java.lang.String getTableNames(int index) {
        return tableNames_.get(index);
      }
      /**
       * <code>repeated string tableNames = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the tableNames at the given index.
       */
      public com.google.protobuf.ByteString
          getTableNamesBytes(int index) {
        return tableNames_.getByteString(index);
      }
      /**
       * <code>repeated string tableNames = 1;</code>
       * @param index The index to set the value at.
       * @param value The tableNames to set.
       * @return This builder for chaining.
       */
      public Builder setTableNames(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTableNamesIsMutable();
        tableNames_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tableNames = 1;</code>
       * @param value The tableNames to add.
       * @return This builder for chaining.
       */
      public Builder addTableNames(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTableNamesIsMutable();
        tableNames_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tableNames = 1;</code>
       * @param values The tableNames to add.
       * @return This builder for chaining.
       */
      public Builder addAllTableNames(
          java.lang.Iterable<java.lang.String> values) {
        ensureTableNamesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tableNames_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tableNames = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTableNames() {
        tableNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tableNames = 1;</code>
       * @param value The bytes of the tableNames to add.
       * @return This builder for chaining.
       */
      public Builder addTableNamesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureTableNamesIsMutable();
        tableNames_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:extracttable.ExtractTableNamesResponse)
    }

    // @@protoc_insertion_point(class_scope:extracttable.ExtractTableNamesResponse)
    private static final com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse();
    }

    public static com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExtractTableNamesResponse>
        PARSER = new com.google.protobuf.AbstractParser<ExtractTableNamesResponse>() {
      @java.lang.Override
      public ExtractTableNamesResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExtractTableNamesResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ExtractTableNamesResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExtractTableNamesResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tktkc72.zetasql_extract_table.ZetasqlExtractTable.ExtractTableNamesResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extracttable_ExtractTableNamesRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extracttable_ExtractTableNamesRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extracttable_ExtractTableNamesResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extracttable_ExtractTableNamesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033zetasql-extract-table.proto\022\014extractta" +
      "ble\"-\n\030ExtractTableNamesRequest\022\021\n\tstate" +
      "ment\030\001 \001(\t\"/\n\031ExtractTableNamesResponse\022" +
      "\022\n\ntableNames\030\001 \003(\t2\214\001\n\036ExtractTableName" +
      "sFromStatement\022j\n\025ExtractTableNamesFrom\022" +
      "&.extracttable.ExtractTableNamesRequest\032" +
      "\'.extracttable.ExtractTableNamesResponse" +
      "\"\000Bg\n!com.tktkc72.zetasql_extract_tableB" +
      "\023ZetasqlExtractTableZ-github.com/tktkc72" +
      "/zetasql-extract-table/grpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_extracttable_ExtractTableNamesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_extracttable_ExtractTableNamesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extracttable_ExtractTableNamesRequest_descriptor,
        new java.lang.String[] { "Statement", });
    internal_static_extracttable_ExtractTableNamesResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_extracttable_ExtractTableNamesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extracttable_ExtractTableNamesResponse_descriptor,
        new java.lang.String[] { "TableNames", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
