// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.4
// source: zetasql-extract-table.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtractTableNamesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Statement string `protobuf:"bytes,1,opt,name=statement,proto3" json:"statement,omitempty"`
}

func (x *ExtractTableNamesRequest) Reset() {
	*x = ExtractTableNamesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zetasql_extract_table_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtractTableNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractTableNamesRequest) ProtoMessage() {}

func (x *ExtractTableNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zetasql_extract_table_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractTableNamesRequest.ProtoReflect.Descriptor instead.
func (*ExtractTableNamesRequest) Descriptor() ([]byte, []int) {
	return file_zetasql_extract_table_proto_rawDescGZIP(), []int{0}
}

func (x *ExtractTableNamesRequest) GetStatement() string {
	if x != nil {
		return x.Statement
	}
	return ""
}

type ExtractTableNamesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableNames []string `protobuf:"bytes,1,rep,name=tableNames,proto3" json:"tableNames,omitempty"`
}

func (x *ExtractTableNamesResponse) Reset() {
	*x = ExtractTableNamesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zetasql_extract_table_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtractTableNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractTableNamesResponse) ProtoMessage() {}

func (x *ExtractTableNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zetasql_extract_table_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractTableNamesResponse.ProtoReflect.Descriptor instead.
func (*ExtractTableNamesResponse) Descriptor() ([]byte, []int) {
	return file_zetasql_extract_table_proto_rawDescGZIP(), []int{1}
}

func (x *ExtractTableNamesResponse) GetTableNames() []string {
	if x != nil {
		return x.TableNames
	}
	return nil
}

var File_zetasql_extract_table_proto protoreflect.FileDescriptor

var file_zetasql_extract_table_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x7a, 0x65, 0x74, 0x61, 0x73, 0x71, 0x6c, 0x2d, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x2d, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x65,
	0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x38, 0x0a, 0x18, 0x45,
	0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x3b, 0x0a, 0x19, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x32, 0x8c, 0x01, 0x0a, 0x1e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x6a, 0x0a, 0x15, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x26,
	0x2e, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x45, 0x78,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x67, 0x0a, 0x21, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x6b, 0x74, 0x6b, 0x63, 0x37, 0x32,
	0x2e, 0x7a, 0x65, 0x74, 0x61, 0x73, 0x71, 0x6c, 0x2d, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x2d, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x13, 0x5a, 0x65, 0x74, 0x61, 0x73, 0x71, 0x6c, 0x45,
	0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x5a, 0x2d, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x6b, 0x74, 0x6b, 0x63, 0x37, 0x32, 0x2f,
	0x7a, 0x65, 0x74, 0x61, 0x73, 0x71, 0x6c, 0x2d, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2d,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_zetasql_extract_table_proto_rawDescOnce sync.Once
	file_zetasql_extract_table_proto_rawDescData = file_zetasql_extract_table_proto_rawDesc
)

func file_zetasql_extract_table_proto_rawDescGZIP() []byte {
	file_zetasql_extract_table_proto_rawDescOnce.Do(func() {
		file_zetasql_extract_table_proto_rawDescData = protoimpl.X.CompressGZIP(file_zetasql_extract_table_proto_rawDescData)
	})
	return file_zetasql_extract_table_proto_rawDescData
}

var file_zetasql_extract_table_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_zetasql_extract_table_proto_goTypes = []interface{}{
	(*ExtractTableNamesRequest)(nil),  // 0: extracttable.ExtractTableNamesRequest
	(*ExtractTableNamesResponse)(nil), // 1: extracttable.ExtractTableNamesResponse
}
var file_zetasql_extract_table_proto_depIdxs = []int32{
	0, // 0: extracttable.ExtractTableNamesFromStatement.ExtractTableNamesFrom:input_type -> extracttable.ExtractTableNamesRequest
	1, // 1: extracttable.ExtractTableNamesFromStatement.ExtractTableNamesFrom:output_type -> extracttable.ExtractTableNamesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zetasql_extract_table_proto_init() }
func file_zetasql_extract_table_proto_init() {
	if File_zetasql_extract_table_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zetasql_extract_table_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtractTableNamesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zetasql_extract_table_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtractTableNamesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zetasql_extract_table_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zetasql_extract_table_proto_goTypes,
		DependencyIndexes: file_zetasql_extract_table_proto_depIdxs,
		MessageInfos:      file_zetasql_extract_table_proto_msgTypes,
	}.Build()
	File_zetasql_extract_table_proto = out.File
	file_zetasql_extract_table_proto_rawDesc = nil
	file_zetasql_extract_table_proto_goTypes = nil
	file_zetasql_extract_table_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ExtractTableNamesFromStatementClient is the client API for ExtractTableNamesFromStatement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExtractTableNamesFromStatementClient interface {
	ExtractTableNamesFrom(ctx context.Context, in *ExtractTableNamesRequest, opts ...grpc.CallOption) (*ExtractTableNamesResponse, error)
}

type extractTableNamesFromStatementClient struct {
	cc grpc.ClientConnInterface
}

func NewExtractTableNamesFromStatementClient(cc grpc.ClientConnInterface) ExtractTableNamesFromStatementClient {
	return &extractTableNamesFromStatementClient{cc}
}

func (c *extractTableNamesFromStatementClient) ExtractTableNamesFrom(ctx context.Context, in *ExtractTableNamesRequest, opts ...grpc.CallOption) (*ExtractTableNamesResponse, error) {
	out := new(ExtractTableNamesResponse)
	err := c.cc.Invoke(ctx, "/extracttable.ExtractTableNamesFromStatement/ExtractTableNamesFrom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExtractTableNamesFromStatementServer is the server API for ExtractTableNamesFromStatement service.
type ExtractTableNamesFromStatementServer interface {
	ExtractTableNamesFrom(context.Context, *ExtractTableNamesRequest) (*ExtractTableNamesResponse, error)
}

// UnimplementedExtractTableNamesFromStatementServer can be embedded to have forward compatible implementations.
type UnimplementedExtractTableNamesFromStatementServer struct {
}

func (*UnimplementedExtractTableNamesFromStatementServer) ExtractTableNamesFrom(context.Context, *ExtractTableNamesRequest) (*ExtractTableNamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExtractTableNamesFrom not implemented")
}

func RegisterExtractTableNamesFromStatementServer(s *grpc.Server, srv ExtractTableNamesFromStatementServer) {
	s.RegisterService(&_ExtractTableNamesFromStatement_serviceDesc, srv)
}

func _ExtractTableNamesFromStatement_ExtractTableNamesFrom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractTableNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractTableNamesFromStatementServer).ExtractTableNamesFrom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/extracttable.ExtractTableNamesFromStatement/ExtractTableNamesFrom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractTableNamesFromStatementServer).ExtractTableNamesFrom(ctx, req.(*ExtractTableNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExtractTableNamesFromStatement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "extracttable.ExtractTableNamesFromStatement",
	HandlerType: (*ExtractTableNamesFromStatementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExtractTableNamesFrom",
			Handler:    _ExtractTableNamesFromStatement_ExtractTableNamesFrom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zetasql-extract-table.proto",
}
